spring:
  application:
    name: notification-service

  mail:
    host: {HOST_MAIL}
    port: {PORT_MAIL}
    username: {USERNAME_MAIL}
    password: {PASSWORD_MAIL}
    properties.mail.smtp.auth: {true}
    properties.mail.smtp.starttls.enable: {true}

