spring:
  application:
    name: gateway-service
  rabbitmq:
    host: ${HOST_RMQ:localhost}
    port: ${PORT_RMQ:5672}
    username: ${USERNAME_RMQ:guest}
    password: ${PASSWORD_RMQ:guest}
    virtual-host: /
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-create-user
              uri: no-op://localhost
              predicates:
                - Path=/api/v1/auth/create-user
                - Method=POST
              filters:
                - CreateUserProducer
    stream:
      bindings:
        createUserProducer-out-0:
          destination: exchange-auth-service
