server:
  port: 8081
jwt:
  secrete:
    key: "${JWT_SECRETE_KEY:secreteKeyDefaultWith123456789012}"
spring:
  application:
    name: gateway-service
  rabbitmq:
    host: ${HOST_RMQ:localhost}
    port: ${PORT_RMQ:5672}
    username: ${USERNAME_RMQ:guest}
    password: ${PASSWORD_RMQ:guest}
    virtual-host: /
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-create-user
              uri: no-op://localhost
              predicates:
                - Path=/api/v1/auth/create-user
                - Method=POST
              filters:
                - CreateUserProducer
            - id: auth-service-authentication
              uri: grpc://localhost:9090
              predicates:
                - Path=/api/v1/auth/authentication
                - Method=POST
              filters:
                - name: JsonToGrpc
                  args:
                    service: AuthService
                    method: Authentication
                    protoDescriptor: classpath:all-services.pb
    stream:
      bindings:
        createUserProducer-out-0:
          destination: exchange-auth-service
