server:
  port: 8088

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  threads:
    virtual:
      enabled: true

  application:
    name: service-bancary

  datasource:
    url: ${URL_SERVICE_BANCARY_DB:jdbc:postgresql://localhost:5432/service-bancary}
    username: "${USERNAME_SERVICE_BANCARY_DB:user}"
    password: "${PASSWORD_SERVICE_BANCARY_DB:password}"
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: 5672
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}
    virtual-host: /

  cloud:
    function:
      definition:
        createAccountConsumer;
        depositAccountConsumer;
        withdrawAccountConsumer;
        transferMoneyAccountConsumer;
        createUserConsumer;
        createHistoryConsumer;
        schedulingTransferConsumer;
        updateDateSchedulingTransferConsumer;
        deleteSchedulingTransferConsumer
    stream:
      default:
        consumer:
          max-attempts: 3
          backOffInitialInterval: 5000
          error-channel-enabled: true
          retryable-exceptions:
            java.lang.IllegalArgumentException: false
            java.time.format.DateTimeParseException: false
            org.springframework.dao.DataIntegrityViolationException: false
            dev.cruzs.gustavo.service_bancary.account.domain.exceptions.DuplicateAttributeAccountException: false
            dev.cruzs.gustavo.service_bancary.user.domain.exceptions.DuplicateAttributeUserException: false
      bindings:
        createAccountConsumer-in-0:
          destination: exchange-account-bancary
          group: queue-create-account
        depositAccountConsumer-in-0:
          destination: exchange-account-bancary
          group: queue-deposit-account
        withdrawAccountConsumer-in-0:
          destination: exchange-account-bancary
          group: queue-withdraw-acount
        transferMoneyAccountConsumer-in-0:
          destination: exchange-account-bancary
          group: queue-transferMoney-account
        createUserConsumer-in-0:
          destination: exchange-user
          group: queue-create-user
        createHistoryConsumer-in-0:
          destination: exchange-history
          group: queue-create-history
        schedulingTransferConsumer-in-0:
          destination: exchange-scheduling
          group: queue-transfer-scheduling
        updateDateSchedulingTransferConsumer-in-0:
          destination: exchange-scheduling
          group: queue-update-transfer-scheduling
        deleteSchedulingTransferConsumer-in-0:
          destination: exchange-scheduling
          group: queue-delete-transfer-scheduling

        createHistoryProducer-out-0:
          destination: exchange-history
        sendEmailProducer-out-0:
          destination: exchange-notification
        transferMoneyAccountProducer-out-0:
          destination: exchange-account-bancary
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            republish-to-dlq: true
        bindings:
          createAccountConsumer-in-0:
            consumer:
              binding-routing-key: rk-create-account
          depositAccountConsumer-in-0:
            consumer:
              binding-routing-key: rk-deposit-account
          withdrawAccountConsumer-in-0:
            consumer:
              binding-routing-key: rk-withdraw-account
          transferMoneyAccountConsumer-in-0:
            consumer:
              binding-routing-key: rk-transfer-money
          createUserConsumer-in-0:
            consumer:
              binding-routing-key: rk-create-user
          createHistoryConsumer-in-0:
            consumer:
              binding-routing-key: rk-create-history
          schedulingTransferConsumer-in-0:
            consumer:
              binding-routing-key: rk-tranfer-scheduling
          updateDateSchedulingTransferConsumer-in-0:
            consumer:
              binding-routing-key: rk-update-tranfer-scheduling
          deleteSchedulingTransferConsumer-in-0:
            consumer:
              binding-routing-key: rk-delete-tranfer-scheduling

          createHistoryProducer-out-0:
            producer:
              routing-key-expression: "'rk-create-history'"
          transferMoneyAccountProducer-out-0:
            producer:
              routing-key-expression: "'rk-transfer-money'"

grpc:
  client:
    history-service:
      address: "${GRPC_HISTORY_SERVICE_ADDRESS:static://localhost:9090}"
      negotiation-type: plaintext
    user-service:
      address: "${GRPC_USER_SERVICE_ADDRESS:static://localhost:9090}"
      negotiation-type: plaintext
