spring:
  application:
    name: service-bancary

  datasource:
    url: jdbc:postgresql://localhost:5432/service-bancary
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  cloud:
    function:
      definition: createAccountConsumer;depositAccountConsumer;withdrawAccountConsumer;transferMoneyAccountConsumer
    stream:
      default:
        consumer:
          max-attempts: 3
          backOffInitialInterval: 5000
          error-channel-enabled: true
          retryable-exceptions:
            java.lang.IllegalArgumentException: false
            org.springframework.dao.DataIntegrityViolationException: false
            dev.cruzs.gustavo.service_bancary.account.domain.exceptions.DuplicateAccountException: false
      bindings:
        createAccountConsumer-in-0:
          destination: exchange-account-bancary
          group: queue-create-account
        depositAccountConsumer-in-0:
          destination: exchange-account-bancary
          group: queue-deposit-account
        withdrawAccountConsumer-in-0:
          destination: exchange-account-bancary
          group: queue-withdraw-acount
        transferMoneyAccountConsumer-in-0:
          destination: exchange-account-bancary
          group: queue-transferMoney-account
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            republish-to-dlq: true
