syntax = "proto3";

option java_multiple_files = true;
option java_package = "dev.cruzs.gustavo.gateway_service.filters.gRPC.generated";

message HistoryResponse {
  string id = 1;
  string account_id = 2;
  string amount = 3;
  string institution_name = 4;
  string destinatary_name = 5;
  string transfer_date = 6;
}

message FindAllByAccountIdOrDestinataryNameAndYearMonthRequest {
  string account_id = 1;
  string destinatary_name = 2;
  string year_month = 3;
}

message FindHistoryByIdRequest {
  string id = 1;
}

message ListHistoriesResponse {
  repeated HistoryResponse histories_response = 1;
}

service HistoryService {
  rpc findAllByAccountIdOrDestinataryNameAndYearMonth (FindAllByAccountIdOrDestinataryNameAndYearMonthRequest) returns (ListHistoriesResponse);
  rpc FindHistoryById (FindHistoryByIdRequest) returns (HistoryResponse);
}
